
import __ASTRO_IMAGE_IMPORT_1WygnF from "../../assets/architecture.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_10ES8j from "../../../assets/uml.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fdatamigrato%2Flld.md";
import __ASTRO_IMAGE_IMPORT_2m7MVf from "../../../assets/arc_1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Farchitecture.md";
import __ASTRO_IMAGE_IMPORT_UMiaY from "../../../assets/arc_2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Farchitecture.md";
import __ASTRO_IMAGE_IMPORT_Zuxczh from "../../../assets/arc_3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Farchitecture.md";
import __ASTRO_IMAGE_IMPORT_ZpJF3G from "../../../assets/lld_data1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Flld.md";
import __ASTRO_IMAGE_IMPORT_SknqE from "../../../assets/lld_data2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Flld.md";
import __ASTRO_IMAGE_IMPORT_Z2nqhxc from "../../../assets/wire_1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Fwireframe.md";
import __ASTRO_IMAGE_IMPORT_Z1rPYnU from "../../../assets/wire_2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Fwireframe.md";
import __ASTRO_IMAGE_IMPORT_ZwgGeD from "../../../assets/wire_3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Fwireframe.md";
import __ASTRO_IMAGE_IMPORT_Z1GSHK3 from "../../../assets/hld_img1b.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Fhld.md";
import __ASTRO_IMAGE_IMPORT_Z1jOCSS from "../../../assets/hld_img2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Fhld.md";
export default new Map([["../../assets/architecture.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1WygnF], ["../../../assets/uml.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fdatamigrato%2Flld.md", __ASTRO_IMAGE_IMPORT_10ES8j], ["../../../assets/arc_1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Farchitecture.md", __ASTRO_IMAGE_IMPORT_2m7MVf], ["../../../assets/arc_2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Farchitecture.md", __ASTRO_IMAGE_IMPORT_UMiaY], ["../../../assets/arc_3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Farchitecture.md", __ASTRO_IMAGE_IMPORT_Zuxczh], ["../../../assets/lld_data1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Flld.md", __ASTRO_IMAGE_IMPORT_ZpJF3G], ["../../../assets/lld_data2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Flld.md", __ASTRO_IMAGE_IMPORT_SknqE], ["../../../assets/wire_1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Fwireframe.md", __ASTRO_IMAGE_IMPORT_Z2nqhxc], ["../../../assets/wire_2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Fwireframe.md", __ASTRO_IMAGE_IMPORT_Z1rPYnU], ["../../../assets/wire_3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Fwireframe.md", __ASTRO_IMAGE_IMPORT_ZwgGeD], ["../../../assets/hld_img1b.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Fhld.md", __ASTRO_IMAGE_IMPORT_Z1GSHK3], ["../../../assets/hld_img2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fguides%2Fhld.md", __ASTRO_IMAGE_IMPORT_Z1jOCSS]]);
		